<?php
/**
 * @file
 * Code for the CRF Cluster Content feature.
 */

include_once 'crf_cluster_content.features.inc';


/**
 * Implements hook_form_FORM_ID_alter().
 */
function crf_cluster_content_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  // Convert request exposed filter text field into a dropdown
  // list pre-populated with all requests.
  if ($form['#id'] == 'views-exposed-form-cluster-content-page') {
    $options = array('' => t('- Any -'));
    $query = new EntityFieldQuery();
    $result = $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'crf_request')
      ->execute();
    if (!empty($result['node'])) {        
      $nodes = node_load_multiple(array_keys($result['node']));
      foreach ($nodes as $nid => $node) {
        $options[$nid] = $node->title;
      }
    }    
    $form['field_crf_request_target_id']['#type'] = 'select';
    $form['field_crf_request_target_id']['#size'] = 1;
    $form['field_crf_request_target_id']['#options'] = $options;
  }
}

